#!/usr/bin/env python
"""Additional calibration, diagnostic, and reproducibility analyses.

This script supplements the primary pipeline with standard calibration
baselines, mask-aware learned reduced-item comparators, per-class and high-risk
error tables, response-time residual diagnostics, calibration-delta bootstrap checks, and a stepwise
future-information perturbation audit.  It
uses only the public raw CSV files and participant-disjoint train/validation/
test splits generated by the main pipeline.
"""
from __future__ import annotations

import json
import math
import os
import sys
import time
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.isotonic import IsotonicRegression
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import (
    average_precision_score,
    confusion_matrix,
    f1_score,
    log_loss,
    mean_absolute_error,
    precision_recall_fscore_support,
    recall_score,
    roc_auc_score,
)
from sklearn.preprocessing import OneHotEncoder

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from rt_screening.engine import (  # noqa:E402
    ITEM_ORDER,
    ITEM_TO_SCALE,
    SCALE_NAMES,
    SCALE_ORDER,
    SCALES,
    _labels_for_scores,
    _probs_for_scores,
    _probs_for_scores_variable_sigma,
    _scores_from_selected,
    _sigma_multiplier_for_variant,
    aggregate_metrics,
    build_long_format,
    create_splits,
    ece_score,
    ensure_dirs,
    evaluate_policy,
    fit_rt_residuals,
    get_calibration_sigmas,
    item_info_values,
    load_config,
    load_ids,
    make_targets_frame,
    per_scale_metrics,
    root_path,
    run_main_models,
    simulate_item_selection,
)

TABLE_DIR = ROOT / "results" / "tables"
FIG_DIR = ROOT / "results" / "figures"
SUPP_FIG_DIR = ROOT / "results" / "supplementary_figures"
SUPP_FIG_DIR.mkdir(parents=True, exist_ok=True)


def _ensure_predictions(long: pd.DataFrame) -> None:
    """Ensure prediction CSV files needed for bootstrap and new analyses exist."""
    needed = [
        TABLE_DIR / "predictions_response_only_uncertainty_b19_responses.csv",
        TABLE_DIR / "predictions_response_only_uncertainty_b19_responses_rt_calibration_only.csv",
        TABLE_DIR / "predictions_rt_aware_uncertainty_b19_responses_rt_state.csv",
    ]
    if not all(p.exists() for p in needed):
        print("Regenerating main-model predictions...", flush=True)
        run_main_models(long)


def _temperature_scale(prob: np.ndarray, temperature: float) -> np.ndarray:
    prob = np.clip(prob, 1e-12, 1.0)
    logits = np.log(prob) / float(temperature)
    logits -= logits.max(axis=1, keepdims=True)
    ex = np.exp(logits)
    return ex / ex.sum(axis=1, keepdims=True)


def ece_score_with_fixed_pred(y: np.ndarray, prob: np.ndarray, pred: np.ndarray, n_bins: int = 10) -> float:
    """Label-aware ECE using the probability assigned to the issued label.

    This is the primary ECE for label-preserving calibration controls. It avoids
    mixing an unchanged issued label with the calibrated probability argmax when
    post-hoc calibration changes the highest-probability class.
    """
    pred = np.asarray(pred).astype(int)
    y = np.asarray(y).astype(int)
    conf = np.clip(prob[np.arange(len(y)), pred], 0.0, 1.0)
    correct = (pred == y).astype(float)
    bins = np.linspace(0, 1, n_bins + 1)
    ece = 0.0
    for lo, hi in zip(bins[:-1], bins[1:]):
        mask = (conf > lo) & (conf <= hi)
        if mask.any():
            ece += float(mask.mean() * abs(correct[mask].mean() - conf[mask].mean()))
    return float(ece)


def adaptive_ece_score(y: np.ndarray, prob: np.ndarray, pred: np.ndarray | None = None, n_bins: int = 10) -> float:
    """ECE with equal-frequency confidence bins.

    When ``pred`` is provided, confidence is the probability assigned to that
    fixed issued label; otherwise the calibrated probability argmax is used.
    """
    if pred is None:
        pred = prob.argmax(axis=1)
        conf = prob.max(axis=1)
    else:
        pred = np.asarray(pred).astype(int)
        conf = np.clip(prob[np.arange(len(y)), pred], 0.0, 1.0)
    correct = (pred == y).astype(float)
    order = np.argsort(conf)
    splits = np.array_split(order, n_bins)
    ece = 0.0
    n = len(y)
    for idx in splits:
        if len(idx) == 0:
            continue
        ece += (len(idx) / n) * abs(float(correct[idx].mean()) - float(conf[idx].mean()))
    return float(ece)


def classwise_ece_score(y: np.ndarray, prob: np.ndarray, n_bins: int = 10) -> float:
    """Mean one-vs-rest ECE across classes."""
    vals = []
    bins = np.linspace(0, 1, n_bins + 1)
    for c in range(prob.shape[1]):
        p = prob[:, c]
        observed = (y == c).astype(float)
        ece = 0.0
        for lo, hi in zip(bins[:-1], bins[1:]):
            mask = (p > lo) & (p <= hi)
            if mask.any():
                ece += float(mask.mean() * abs(observed[mask].mean() - p[mask].mean()))
        vals.append(ece)
    return float(np.mean(vals))


def multiclass_nll(y: np.ndarray, prob: np.ndarray) -> float:
    labels = list(range(prob.shape[1]))
    return float(log_loss(y, np.clip(prob, 1e-12, 1.0), labels=labels))


def _metric_bundle(ytrue: pd.DataFrame, pred: Dict[str, np.ndarray], prob: Dict[str, np.ndarray]) -> Dict[str, float]:
    cfg = load_config()
    rows = []
    for sc in SCALE_ORDER:
        y = ytrue[f"{sc}_severity_idx"].astype(int).values
        p = np.asarray(pred[sc]).astype(int)
        pr = np.asarray(prob[sc], dtype=float)
        high = cfg["labels"][sc]["high_risk_index"]
        eye = np.eye(pr.shape[1])
        argmax_pred = pr.argmax(axis=1)
        rows.append({
            "scale": sc,
            "macro_f1": float(f1_score(y, p, average="macro", zero_division=0)),
            "mae": float(mean_absolute_error(y, p)),
            "high_risk_recall": float(recall_score(y >= high, p >= high, zero_division=0)),
            "brier_score": float(np.mean(np.sum((pr - eye[y]) ** 2, axis=1))),
            # Primary ECE: confidence assigned to the issued label.
            "ece": ece_score_with_fixed_pred(y, pr, p),
            "ece_argmax": ece_score(y, pr),
            "adaptive_ece": adaptive_ece_score(y, pr, p),
            "adaptive_ece_argmax": adaptive_ece_score(y, pr),
            "classwise_ece": classwise_ece_score(y, pr),
            "nll": multiclass_nll(y, pr),
            "argmax_change_rate": float(np.mean(argmax_pred != p)),
        })
    df = pd.DataFrame(rows)
    return {f"mean_{c}": float(df[c].mean()) for c in [
        "macro_f1", "mae", "high_risk_recall", "brier_score", "ece",
        "ece_argmax", "adaptive_ece", "adaptive_ece_argmax", "classwise_ece",
        "nll", "argmax_change_rate"
    ]}




def _bootstrap_calibration_deltas(
    ytrue: pd.DataFrame,
    method_payloads: Dict[str, Tuple[Dict[str, np.ndarray], Dict[str, np.ndarray]]],
    n_boot: int = 200,
) -> pd.DataFrame:
    """Participant-level bootstrap CIs for label-aware ECE deltas."""
    rng = np.random.default_rng(load_config()["seed"] + 2027)
    n = len(ytrue)
    comparisons = [
        ("true_rt_calibration_only_minus_response_only", "true_rt_calibration_only", "response_only_uncalibrated"),
        ("constant_softening_minus_response_only", "constant_softening", "response_only_uncalibrated"),
        ("temperature_scaling_minus_response_only", "temperature_scaling", "response_only_uncalibrated"),
        ("one_vs_rest_isotonic_minus_response_only", "one_vs_rest_isotonic", "response_only_uncalibrated"),
        ("true_rt_calibration_only_minus_constant_softening", "true_rt_calibration_only", "constant_softening"),
        ("true_rt_calibration_only_minus_isotonic", "true_rt_calibration_only", "one_vs_rest_isotonic"),
    ]

    def mean_ece_for(method: str, idx: np.ndarray) -> float:
        pred, prob = method_payloads[method]
        vals = []
        for sc in SCALE_ORDER:
            y = ytrue[f"{sc}_severity_idx"].astype(int).values[idx]
            vals.append(ece_score_with_fixed_pred(y, prob[sc][idx], pred[sc][idx]))
        return float(np.mean(vals))

    rows = []
    for label, a, b in comparisons:
        deltas = []
        for _ in range(n_boot):
            idx = rng.integers(0, n, n)
            deltas.append(mean_ece_for(a, idx) - mean_ece_for(b, idx))
        arr = np.asarray(deltas, dtype=float)
        rows.append({
            "comparison": label,
            "metric": "mean_label_aware_ece_delta",
            "delta_mean": float(arr.mean()),
            "ci_lower_2p5": float(np.quantile(arr, 0.025)),
            "ci_upper_97p5": float(np.quantile(arr, 0.975)),
            "bootstrap_repeats": int(n_boot),
        })
    out = pd.DataFrame(rows)
    out.to_csv(TABLE_DIR / "table13_calibration_delta_bootstrap_19.csv", index=False)
    return out


def _fast_response_policy_selection(policy: str, budget: int, ids: Iterable[int], long: pd.DataFrame, seed: int) -> Dict[int, List[str]]:
    """Vectorized equivalent of response/RT-aware uncertainty item selection.

    The main engine keeps a transparent reference implementation. This helper is
    used only for the additional 19-item sensitivity analyses so the compact
    release can recompute reviewer-requested checks without repeatedly looping
    over participants in Python. It preserves the selected item set used by the
    reference policy; prediction functions depend on the selected set rather
    than on reveal order.
    """
    if policy not in {"response_only_uncertainty", "rt_aware_uncertainty", "rt_only_uncertainty"}:
        return simulate_item_selection(policy, budget, ids, long=long, seed=seed)
    ids = list(map(int, ids))
    use_rt = policy in {"rt_aware_uncertainty", "rt_only_uncertainty"}
    info = item_info_values(long)
    info_map = dict(zip(info["global_item_id"], info["rank_score"]))
    info_scores = np.array([info_map.get(item, 0.0) for item in ITEM_ORDER], dtype=float)
    top_by_scale = {sc: info[info["scale"] == sc]["global_item_id"].tolist() for sc in SCALE_ORDER}
    warm_idx = []
    for sc in SCALE_ORDER:
        if top_by_scale[sc]:
            warm_idx.append(ITEM_ORDER.index(top_by_scale[sc][0]))
    warm_idx = warm_idx[:min(len(warm_idx), budget)]
    subset = long[long["participant_id"].isin(ids)]
    resp_mat = subset.pivot(index="participant_id", columns="global_item_id", values="item_response").reindex(index=ids, columns=ITEM_ORDER).to_numpy(dtype=float)
    resid_mat = subset.pivot(index="participant_id", columns="global_item_id", values="rt_residual_content_z").reindex(index=ids, columns=ITEM_ORDER).to_numpy(dtype=float)
    item_scale_idx = np.array([SCALE_ORDER.index(ITEM_TO_SCALE[item]) for item in ITEM_ORDER])
    scale_item_masks = np.stack([item_scale_idx == si for si in range(len(SCALE_ORDER))], axis=0)
    cutoffs = {sc: np.array(load_config()["labels"][sc]["cutoffs"][1:-1], dtype=float) for sc in SCALE_ORDER}
    selected_mask = np.zeros((len(ids), len(ITEM_ORDER)), dtype=bool)
    selected_mask[:, warm_idx] = True
    pid_arr = np.array(ids, dtype=int)
    while selected_mask.sum(axis=1).min() < budget:
        counts = selected_mask.astype(float) @ scale_item_masks.T.astype(float)
        scale_unc = np.ones((len(ids), len(SCALE_ORDER)), dtype=float) * 2.0
        for si, sc in enumerate(SCALE_ORDER):
            mask = selected_mask & scale_item_masks[si]
            cnt = counts[:, si]
            has = cnt > 0
            vals = np.where(mask, resp_mat, 0.0)
            s_resp = vals.sum(axis=1)
            mean = np.zeros(len(ids), dtype=float)
            mean[has] = s_resp[has] / cnt[has]
            ss_resp = np.where(mask, resp_mat ** 2, 0.0).sum(axis=1)
            var = np.zeros(len(ids), dtype=float)
            var[has] = np.maximum(ss_resp[has] / cnt[has] - mean[has] ** 2, 0.0)
            std = np.sqrt(var)
            est = mean * SCALES[sc] - (14 if sc == "pss" else 0)
            boundaries = cutoffs[sc]
            dist = np.min(np.abs(est[:, None] - boundaries[None, :]), axis=1) if len(boundaries) else np.full(len(ids), 3.0)
            unc = (1.0 / (1.0 + dist)) + (1.0 - cnt / SCALES[sc]) + 0.10 * std
            scale_unc[has, si] = unc[has]
        reliability = np.ones(len(ids), dtype=float)
        if use_rt:
            cnt_all = selected_mask.sum(axis=1).astype(float)
            fast = ((resid_mat < -1) & selected_mask).sum(axis=1) / cnt_all
            long_pause = ((resid_mat > 1) & selected_mask).sum(axis=1) / cnt_all
            vals = np.where(selected_mask, resid_mat, 0.0)
            mean = vals.sum(axis=1) / cnt_all
            ss = np.where(selected_mask, resid_mat ** 2, 0.0).sum(axis=1)
            std = np.sqrt(np.maximum(ss / cnt_all - mean ** 2, 0.0))
            reliability = np.clip(1.0 - 0.35 * fast - 0.20 * long_pause - 0.08 * np.minimum(std, 4.0), 0.10, 1.0)
            scale_unc *= (1.0 + 0.25 * np.maximum(0.0, 1.0 - reliability))[:, None]
        unreliability = np.maximum(0.0, 1.0 - reliability)
        counts_min = counts.min(axis=1)
        scores = np.empty((len(ids), len(ITEM_ORDER)), dtype=float)
        for j in range(len(ITEM_ORDER)):
            si = item_scale_idx[j]
            coverage_gap = 1.0 - counts[:, si] / SCALES[SCALE_ORDER[si]]
            undercovered = (counts[:, si] <= counts_min).astype(float)
            lambda_t = 0.20 + (0.40 * unreliability if use_rt else 0.0)
            rho_t = 0.015 + (0.020 * unreliability if use_rt else 0.0)
            eta_t = 0.00 + (0.25 * unreliability if use_rt else 0.0)
            item_scores = info_scores[j] * (1.0 + scale_unc[:, si])
            item_scores += lambda_t * coverage_gap + 0.08 * undercovered
            item_scores += eta_t * info_scores[j] * (1.0 + undercovered)
            item_scores -= rho_t * counts[:, si]
            item_scores += ((pid_arr * (j + 7)) % 19) * 1e-6
            scores[:, j] = item_scores
        scores[selected_mask] = -1e12
        next_idx = scores.argmax(axis=1)
        selected_mask[np.arange(len(ids)), next_idx] = True
    return {int(pid): [ITEM_ORDER[i] for i in np.where(selected_mask[r])[0]][:budget] for r, pid in enumerate(ids)}

def _pred_prob_from_variant(policy: str, budget: int, variant: str, split: str, long: pd.DataFrame, seed: int) -> Tuple[List[int], pd.DataFrame, Dict[str, np.ndarray], Dict[str, np.ndarray]]:
    ids = load_ids(split)
    selected = simulate_item_selection(policy, budget, ids, long=long, seed=seed)
    sigma_map = get_calibration_sigmas(policy, budget, variant, long) if split == "test" else {sc: 2.5 for sc in SCALE_ORDER}
    from rt_screening.engine import predict_from_selected
    pred, prob, _ = predict_from_selected(ids, selected, variant, long=long, sigma_map=sigma_map)
    targets = make_targets_frame().set_index("participant_id").loc[ids]
    return ids, targets, pred, prob


def run_standard_calibration_baselines(long: pd.DataFrame) -> pd.DataFrame:
    """Run standard post-hoc calibration controls at the 19-item budget."""
    budget = 19
    seed = load_config()["seed"] + budget
    val_ids = load_ids("val")
    test_ids = load_ids("test")
    print("  standard: selecting validation", flush=True)
    selected_val = simulate_item_selection("response_only_uncertainty", budget, val_ids, long=long, seed=seed)
    print("  standard: selecting test", flush=True)
    selected_test = simulate_item_selection("response_only_uncertainty", budget, test_ids, long=long, seed=seed)
    print("  standard: loading base sigma", flush=True)
    base_sigma = get_calibration_sigmas("response_only_uncertainty", budget, "responses", long)

    from rt_screening.engine import predict_from_selected
    print("  standard: predicting validation", flush=True)
    pred_val, prob_val, _ = predict_from_selected(val_ids, selected_val, "responses", long=long, sigma_map=base_sigma)
    print("  standard: predicting test", flush=True)
    pred_test, prob_test, _ = predict_from_selected(test_ids, selected_test, "responses", long=long, sigma_map=base_sigma)
    y_val = make_targets_frame().set_index("participant_id").loc[val_ids]
    y_test = make_targets_frame().set_index("participant_id").loc[test_ids]

    # Fit one temperature per scale on validation NLL.
    temps = {}
    for sc in SCALE_ORDER:
        y = y_val[f"{sc}_severity_idx"].astype(int).values
        grid = [0.50, 0.67, 0.75, 1.00, 1.25, 1.50, 1.75, 2.00, 2.50, 3.00, 4.00, 5.00]
        vals = [(T, multiclass_nll(y, _temperature_scale(prob_val[sc], T))) for T in grid]
        temps[sc] = min(vals, key=lambda x: x[1])[0]

    temp_prob = {sc: _temperature_scale(prob_test[sc], temps[sc]) for sc in SCALE_ORDER}
    print("  standard: fitted temperature", flush=True)

    # One-vs-rest isotonic calibration per class, fitted on validation probabilities, then renormalized.
    iso_prob = {}
    for sc in SCALE_ORDER:
        y = y_val[f"{sc}_severity_idx"].astype(int).values
        pval = prob_val[sc]
        ptest = prob_test[sc]
        calibrated_cols = []
        for c in range(pval.shape[1]):
            iso = IsotonicRegression(out_of_bounds="clip", y_min=0.0, y_max=1.0)
            iso.fit(pval[:, c], (y == c).astype(float))
            calibrated_cols.append(iso.transform(ptest[:, c]))
        arr = np.vstack(calibrated_cols).T
        arr = np.clip(arr, 1e-9, None)
        iso_prob[sc] = arr / arr.sum(axis=1, keepdims=True)

    print("  standard: fitted isotonic", flush=True)
    rows = []
    method_payloads: Dict[str, Tuple[Dict[str, np.ndarray], Dict[str, np.ndarray]]] = {}
    base_pred = {sc: pred_test[sc] for sc in SCALE_ORDER}
    method_payloads["response_only_uncalibrated"] = (base_pred, prob_test)
    method_payloads["temperature_scaling"] = (base_pred, temp_prob)
    method_payloads["one_vs_rest_isotonic"] = (base_pred, iso_prob)
    rows.append({"calibration_method": "response_only_uncalibrated", "uses_true_rt": "No", "label_preserved": "Yes", **_metric_bundle(y_test, base_pred, prob_test)})
    rows.append({"calibration_method": "temperature_scaling", "uses_true_rt": "No", "label_preserved": "Yes", **_metric_bundle(y_test, base_pred, temp_prob)})
    rows.append({"calibration_method": "one_vs_rest_isotonic", "uses_true_rt": "No", "label_preserved": "Yes", **_metric_bundle(y_test, base_pred, iso_prob)})

    # Calibration-only controls share the same selected response prefix and
    # issued labels.  Probabilistic calibration is evaluated both against the
    # calibrated argmax and against the preserved issued label confidence.
    scores_cal, state_cal = _scores_from_selected(test_ids, selected_test, "responses_rt_calibration_only", long)
    for method, variant, uses_rt in [
        ("constant_softening", "responses_constant_softening", "No"),
        ("shuffled_rt_placebo", "responses_shuffled_rt_calibration", "Shuffled"),
        ("true_rt_calibration_only", "responses_rt_calibration_only", "Yes"),
    ]:
        print(f"  standard: {method}", flush=True)
        sigma_map = get_calibration_sigmas("response_only_uncertainty", budget, variant, long)
        pprob = {}
        for sc in SCALE_ORDER:
            mult = _sigma_multiplier_for_variant(variant, sc, scores_cal[sc], state_cal, test_ids)
            pprob[sc] = _probs_for_scores_variable_sigma(sc, scores_cal[sc], float(sigma_map[sc]) * mult)
        method_payloads[method] = (base_pred, pprob)
        rows.append({"calibration_method": method, "uses_true_rt": uses_rt, "label_preserved": "Yes", **_metric_bundle(y_test, base_pred, pprob)})

    # Ensure the label-changing RT score-adjusted row-level prediction file is available.
    _ensure_predictions(long)
    for method, path, uses_rt, preserve in [
        ("rt_score_adjusted", TABLE_DIR / "predictions_rt_aware_uncertainty_b19_responses_rt_state.csv", "Yes", "No"),
    ]:
        print(f"  standard: reading {method}", flush=True)
        dfp = pd.read_csv(path)
        pred = {sc: dfp[f"{sc}_pred"].astype(int).values for sc in SCALE_ORDER}
        prob = {sc: dfp[[c for c in dfp.columns if c.startswith(f"{sc}_prob_")]].values.astype(float) for sc in SCALE_ORDER}
        yt = make_targets_frame().set_index("participant_id").loc[dfp["participant_id"].astype(int).tolist()]
        rows.append({"calibration_method": method, "uses_true_rt": uses_rt, "label_preserved": preserve, **_metric_bundle(yt, pred, prob)})

    _bootstrap_calibration_deltas(y_test, method_payloads, n_boot=200)

    out = pd.DataFrame(rows)
    out["budget"] = budget
    out["validation_temperature_by_scale"] = json.dumps(temps, ensure_ascii=False)
    out.to_csv(TABLE_DIR / "table8_standard_calibration_baselines_19.csv", index=False)
    return out


def _features_for_selected(ids: List[int], selected: Dict[int, List[str]], long: pd.DataFrame) -> pd.DataFrame:
    ids = list(map(int, ids))
    sub = long[long["participant_id"].isin(ids)][["participant_id", "global_item_id", "item_response"]]
    wide = sub.pivot(index="participant_id", columns="global_item_id", values="item_response").reindex(index=ids, columns=ITEM_ORDER).fillna(0.0)
    resp_values = wide.to_numpy(dtype=float)
    mask_values = np.zeros_like(resp_values, dtype=float)
    item_to_idx = {item: i for i, item in enumerate(ITEM_ORDER)}
    for r, pid in enumerate(ids):
        for item in selected[int(pid)]:
            mask_values[r, item_to_idx[item]] = 1.0
    X = np.concatenate([resp_values * mask_values, mask_values], axis=1)
    cols = [f"resp_{item}" for item in ITEM_ORDER] + [f"mask_{item}" for item in ITEM_ORDER]
    return pd.DataFrame(X, index=ids, columns=cols)


def _fit_aligned_model(model, X_train, y_train, X_val, y_val, X_test, n_classes: int) -> Tuple[np.ndarray, np.ndarray, float]:
    """Fit a classifier and return aligned test probabilities and validation NLL."""
    model.fit(X_train, y_train)
    pv = model.predict_proba(X_val)
    aligned_val = np.zeros((len(X_val), n_classes), dtype=float) + 1e-12
    for j, cls in enumerate(model.classes_):
        aligned_val[:, int(cls)] = pv[:, j]
    aligned_val = aligned_val / aligned_val.sum(axis=1, keepdims=True)
    best_nll = multiclass_nll(y_val, aligned_val)
    pt = model.predict_proba(X_test)
    aligned = np.zeros((len(X_test), n_classes), dtype=float) + 1e-12
    for j, cls in enumerate(model.classes_):
        aligned[:, int(cls)] = pt[:, j]
    aligned = aligned / aligned.sum(axis=1, keepdims=True)
    return aligned.argmax(axis=1), aligned, float(best_nll)


def _learned_eval_for_policy(policy: str, budget: int, long: pd.DataFrame, model_kind: str) -> Tuple[dict, pd.DataFrame, pd.DataFrame]:
    cfg = load_config()
    train_ids = load_ids("train")
    val_ids = load_ids("val")
    test_ids = load_ids("test")
    print(f"  learned: selecting {policy} budget {budget} for {model_kind}", flush=True)
    selected_train = simulate_item_selection(policy, budget, train_ids, long=long, seed=cfg["seed"] + budget)
    selected_val = simulate_item_selection(policy, budget, val_ids, long=long, seed=cfg["seed"] + budget)
    selected_test = simulate_item_selection(policy, budget, test_ids, long=long, seed=cfg["seed"] + budget)
    print("  learned: building features", flush=True)
    X_train = _features_for_selected(train_ids, selected_train, long)
    X_val = _features_for_selected(val_ids, selected_val, long)
    X_test = _features_for_selected(test_ids, selected_test, long)
    print(f"  learned: feature shapes {X_train.shape} {X_val.shape} {X_test.shape}", flush=True)
    y_all = make_targets_frame().set_index("participant_id")
    pred: Dict[str, np.ndarray] = {}
    prob: Dict[str, np.ndarray] = {}
    rows = []
    for sc in SCALE_ORDER:
        y_train = y_all.loc[train_ids, f"{sc}_severity_idx"].astype(int).values
        y_val = y_all.loc[val_ids, f"{sc}_severity_idx"].astype(int).values
        classes = np.arange(len(cfg["labels"][sc]["classes"]))
        if model_kind == "cart":
            model = DecisionTreeClassifier(
                max_depth=6,
                min_samples_leaf=40,
                class_weight="balanced",
                random_state=load_config()["seed"] + int(budget) + SCALE_ORDER.index(sc),
            )
            label = "balanced CART, depth 6"
        elif model_kind == "logistic_l2":
            model = OneVsRestClassifier(LogisticRegression(
                C=1.0,
                solver="liblinear",
                max_iter=200,
                class_weight="balanced",
                random_state=load_config()["seed"] + int(budget) + SCALE_ORDER.index(sc),
            ))
            label = "balanced L2 one-vs-rest logistic regression"
        else:
            raise ValueError(model_kind)
        print(f"  learned: fit {sc} {model_kind}", flush=True)
        pred[sc], prob[sc], best_nll = _fit_aligned_model(model, X_train, y_train, X_val, y_val, X_test, len(classes))
        rows.append({"scale": SCALE_NAMES[sc], "model": label, "validation_nll": float(best_nll)})
    targets = y_all.loc[test_ids]
    prefix = {
        "policy": f"{policy}_maskaware_{model_kind}",
        "budget": budget,
        "variant": model_kind,
        "split": "test",
        "n": len(test_ids),
        "avg_items_used": budget,
    }
    scale_df = per_scale_metrics(targets, pred, prob, prefix)
    agg = aggregate_metrics(scale_df); agg.update(prefix)
    details = pd.DataFrame(rows)
    details["policy"] = policy
    details["budget"] = budget
    details["model_kind"] = model_kind
    return agg, scale_df, details

def run_learned_maskaware_baselines(long: pd.DataFrame) -> pd.DataFrame:
    rows = []
    scale_rows = []
    details = []
    for policy in ["train_selected_fixed", "short_forms"]:
        for model_kind in ["cart", "logistic_l2"]:
            for budget in [19]:
                print(f"learned baseline {policy} budget {budget} model {model_kind}", flush=True)
                agg, scdf, det = _learned_eval_for_policy(policy, int(budget), long, model_kind)
                rows.append(agg)
                scale_rows.append(scdf)
                details.append(det)
    out = pd.DataFrame(rows)
    out.to_csv(TABLE_DIR / "table9_learned_maskaware_baselines.csv", index=False)
    pd.concat(scale_rows, ignore_index=True).to_csv(TABLE_DIR / "table9b_learned_maskaware_per_scale.csv", index=False)
    pd.concat(details, ignore_index=True).to_csv(TABLE_DIR / "learned_maskaware_model_selection_19.csv", index=False)
    return out

def run_per_class_error_tables(long: pd.DataFrame) -> None:
    _ensure_predictions(long)
    cfg = load_config()
    variants = [
        ("response_only", TABLE_DIR / "predictions_response_only_uncertainty_b19_responses.csv"),
        ("rt_calibration_only", TABLE_DIR / "predictions_response_only_uncertainty_b19_responses_rt_calibration_only.csv"),
        ("rt_score_adjusted", TABLE_DIR / "predictions_rt_aware_uncertainty_b19_responses_rt_state.csv"),
    ]
    pr_rows = []
    cm_rows = []
    for name, path in variants:
        df = pd.read_csv(path)
        for sc in SCALE_ORDER:
            y = df[f"{sc}_true"].astype(int).values
            p = df[f"{sc}_pred"].astype(int).values
            labels = list(range(len(cfg["labels"][sc]["classes"])))
            prec, rec, f1, sup = precision_recall_fscore_support(y, p, labels=labels, zero_division=0)
            for i, cls_name in enumerate(cfg["labels"][sc]["classes"]):
                pr_rows.append({
                    "variant": name,
                    "scale": SCALE_NAMES[sc],
                    "class_index": i,
                    "severity_label": cls_name,
                    "support": int(sup[i]),
                    "precision": float(prec[i]),
                    "recall": float(rec[i]),
                    "f1": float(f1[i]),
                })
            cm = confusion_matrix(y, p, labels=labels)
            for i, true_label in enumerate(cfg["labels"][sc]["classes"]):
                for j, pred_label in enumerate(cfg["labels"][sc]["classes"]):
                    cm_rows.append({"variant": name, "scale": SCALE_NAMES[sc], "true_label": true_label, "pred_label": pred_label, "count": int(cm[i, j])})
    pd.DataFrame(pr_rows).to_csv(TABLE_DIR / "table10_per_class_metrics_19.csv", index=False)
    pd.DataFrame(cm_rows).to_csv(TABLE_DIR / "table10b_confusion_matrices_19_long.csv", index=False)




def run_high_risk_burden_table(long: pd.DataFrame) -> pd.DataFrame:
    """High-risk binary operating characteristics at the primary 19-item budget."""
    _ensure_predictions(long)
    cfg = load_config()
    variants = [
        ("Response-only", TABLE_DIR / "predictions_response_only_uncertainty_b19_responses.csv"),
        ("RT calibration-only", TABLE_DIR / "predictions_response_only_uncertainty_b19_responses_rt_calibration_only.csv"),
        ("RT score-adjusted", TABLE_DIR / "predictions_rt_aware_uncertainty_b19_responses_rt_state.csv"),
    ]
    rows = []
    for name, path in variants:
        df = pd.read_csv(path)
        for sc in SCALE_ORDER:
            high = int(cfg["labels"][sc]["high_risk_index"])
            y = (df[f"{sc}_true"].astype(int).values >= high).astype(int)
            p = (df[f"{sc}_pred"].astype(int).values >= high).astype(int)
            tp = int(((y == 1) & (p == 1)).sum())
            fp = int(((y == 0) & (p == 1)).sum())
            tn = int(((y == 0) & (p == 0)).sum())
            fn = int(((y == 1) & (p == 0)).sum())
            precision = tp / (tp + fp) if (tp + fp) else 0.0
            recall = tp / (tp + fn) if (tp + fn) else 0.0
            specificity = tn / (tn + fp) if (tn + fp) else 0.0
            fpr = fp / (fp + tn) if (fp + tn) else 0.0
            rows.append({
                "variant": name,
                "scale": SCALE_NAMES[sc],
                "high_risk_threshold_index": high,
                "true_high_risk_n": int(y.sum()),
                "flagged_n": int(p.sum()),
                "tp": tp,
                "fp": fp,
                "tn": tn,
                "fn": fn,
                "high_risk_precision_ppv": float(precision),
                "high_risk_recall_sensitivity": float(recall),
                "specificity": float(specificity),
                "false_positive_rate": float(fpr),
            })
    out = pd.DataFrame(rows)
    out.to_csv(TABLE_DIR / "table12_high_risk_burden_19.csv", index=False)
    return out

def _fit_content_expected(train: pd.DataFrame, apply: pd.DataFrame, lower_pct: float, upper_pct: float, fixed: str) -> Tuple[np.ndarray, np.ndarray, float, float]:
    tr = train.copy(); ap = apply.copy()
    lo, hi = np.percentile(tr["raw_rt"].astype(float), [lower_pct, upper_pct])
    tr["log_rt_tmp"] = np.log1p(tr["raw_rt"].clip(lo, hi))
    ap["log_rt_tmp"] = np.log1p(ap["raw_rt"].clip(lo, hi))
    if fixed == "content":
        Xtr = pd.get_dummies(tr[["word_count", "within_scale_position", "scale"]], columns=["scale"], drop_first=False)
        Xap = pd.get_dummies(ap[["word_count", "within_scale_position", "scale"]], columns=["scale"], drop_first=False).reindex(columns=Xtr.columns, fill_value=0)
        model = LinearRegression().fit(Xtr, tr["log_rt_tmp"])
        exp_tr = model.predict(Xtr); exp_ap = model.predict(Xap)
    elif fixed == "item_fixed":
        means = tr.groupby("global_item_id")["log_rt_tmp"].mean()
        global_mean = float(tr["log_rt_tmp"].mean())
        exp_tr = tr["global_item_id"].map(means).fillna(global_mean).values
        exp_ap = ap["global_item_id"].map(means).fillna(global_mean).values
    elif fixed == "scale_specific":
        exp_tr = np.zeros(len(tr)); exp_ap = np.zeros(len(ap))
        for sc in SCALE_ORDER:
            tr_idx = tr["scale"].values == sc
            ap_idx = ap["scale"].values == sc
            model = LinearRegression().fit(tr.loc[tr_idx, ["word_count", "within_scale_position"]], tr.loc[tr_idx, "log_rt_tmp"])
            exp_tr[tr_idx] = model.predict(tr.loc[tr_idx, ["word_count", "within_scale_position"]])
            exp_ap[ap_idx] = model.predict(ap.loc[ap_idx, ["word_count", "within_scale_position"]])
    else:
        raise ValueError(fixed)
    resid_tr = tr["log_rt_tmp"].values - exp_tr
    mean = float(resid_tr.mean()); sd = float(resid_tr.std(ddof=0) or 1.0)
    z_ap = (ap["log_rt_tmp"].values - exp_ap - mean) / sd
    r2_tr = float(1 - np.sum((tr["log_rt_tmp"].values - exp_tr) ** 2) / np.sum((tr["log_rt_tmp"].values - tr["log_rt_tmp"].mean()) ** 2))
    return z_ap, exp_ap, r2_tr, sd


def _evaluate_rt_cal_only_with_alt_residual(long_alt: pd.DataFrame, budget: int = 19) -> Dict[str, float]:
    cfg = load_config()
    val_ids = load_ids("val"); test_ids = load_ids("test")
    selected_val = _fast_response_policy_selection("response_only_uncertainty", budget, val_ids, long_alt, seed=cfg["seed"] + budget)
    selected_test = _fast_response_policy_selection("response_only_uncertainty", budget, test_ids, long_alt, seed=cfg["seed"] + budget)
    scores_val, state_val = _scores_from_selected(val_ids, selected_val, "responses_rt_calibration_only", long_alt)
    scores_test, state_test = _scores_from_selected(test_ids, selected_test, "responses_rt_calibration_only", long_alt)
    targets_val = make_targets_frame().set_index("participant_id").loc[val_ids]
    targets_test = make_targets_frame().set_index("participant_id").loc[test_ids]
    sigma_map = {}
    for sc in SCALE_ORDER:
        yv = targets_val[f"{sc}_severity_idx"].astype(int).values
        best = (None, math.inf)
        mult = _sigma_multiplier_for_variant("responses_rt_calibration_only", sc, scores_val[sc], state_val, val_ids)
        for sig in cfg.get("calibration_grid", [1, 1.5, 2, 2.5, 3, 4, 5, 6]):
            prob = _probs_for_scores_variable_sigma(sc, scores_val[sc], float(sig) * mult)
            ece = ece_score(yv, prob)
            if ece < best[1]:
                best = (float(sig), float(ece))
        sigma_map[sc] = best[0]
    pred = {}; prob = {}
    for sc in SCALE_ORDER:
        pred[sc] = _labels_for_scores(sc, scores_test[sc])
        mult = _sigma_multiplier_for_variant("responses_rt_calibration_only", sc, scores_test[sc], state_test, test_ids)
        prob[sc] = _probs_for_scores_variable_sigma(sc, scores_test[sc], sigma_map[sc] * mult)
    return _metric_bundle(targets_test, pred, prob)


def run_rt_residual_sensitivity(long: pd.DataFrame) -> pd.DataFrame:
    """Response-time residualization diagnostic and downstream outcome checks."""
    train_ids = set(load_ids("train"))
    train = long[long["participant_id"].isin(train_ids)].copy()
    rows = []
    settings = [
        ("Content model, 0.5-99.5% winsorization", 0.5, 99.5, "content"),
        ("Item fixed-effect model, 0.5-99.5% winsorization", 0.5, 99.5, "item_fixed"),
        ("Scale-specific content model, 0.5-99.5% winsorization", 0.5, 99.5, "scale_specific"),
        ("Content model, 1-99% winsorization", 1.0, 99.0, "content"),
    ]
    for name, lo, hi, kind in settings:
        print(f"RT residual diagnostic and outcome checks: {name}", flush=True)
        long_alt = long.copy()
        z, exp, r2, resid_sd = _fit_content_expected(train, long_alt, lo, hi, kind)
        long_alt["rt_residual_content_z"] = z
        metrics = _evaluate_rt_cal_only_with_alt_residual(long_alt)
        row = {
            "residual_model": name,
            "winsor_lower_pct": lo,
            "winsor_upper_pct": hi,
            "train_R2_log_rt": r2,
            "train_residual_sd": resid_sd,
            "residual_mean_all": float(np.mean(z)),
            "residual_sd_all": float(np.std(z)),
            "residual_q05": float(np.quantile(z, 0.05)),
            "residual_q50": float(np.quantile(z, 0.50)),
            "residual_q95": float(np.quantile(z, 0.95)),
        }
        row.update({f"rt_cal_only_{k}": v for k, v in metrics.items()})
        rows.append(row)
    out = pd.DataFrame(rows)
    out.to_csv(TABLE_DIR / "table11_rt_residual_sensitivity_19.csv", index=False)
    return out


def run_calibration_grid_boundary_sensitivity(long: pd.DataFrame | None = None) -> pd.DataFrame:
    """Expanded calibration-grid sensitivity check at the 19-item budget.

    This analysis extends the original scalar sigma grid from an upper bound of
    6 to 10 and the temperature grid from an upper bound of 5 to 10. It is a
    focused 19-item sensitivity check, not a replacement for the validation-
    selected main tables. The goal is to test whether the qualitative conclusion
    changes when PSS calibration is allowed stronger generic smoothing.
    """
    if long is None:
        long = fit_rt_residuals()
    cfg = load_config()
    budget = 19
    val_ids = load_ids("val")
    test_ids = load_ids("test")
    seed = cfg["seed"] + budget
    selected_val = _fast_response_policy_selection("response_only_uncertainty", budget, val_ids, long, seed=seed)
    selected_test = _fast_response_policy_selection("response_only_uncertainty", budget, test_ids, long, seed=seed)
    targets_val = make_targets_frame().set_index("participant_id").loc[val_ids]
    targets_test = make_targets_frame().set_index("participant_id").loc[test_ids]
    original_sigma_grid = cfg.get("calibration_grid", [1.0, 1.5, 2.0, 2.5, 3.0, 4.0, 5.0, 6.0])
    expanded_sigma_grid = sorted(set([float(x) for x in original_sigma_grid] + [8.0, 10.0]))
    original_temp_grid = [0.50, 0.67, 0.75, 1.00, 1.25, 1.50, 1.75, 2.00, 2.50, 3.00, 4.00, 5.00]
    expanded_temp_grid = sorted(set(original_temp_grid + [6.0, 8.0, 10.0]))

    def _select_sigma(scores, state, variant, grid, sc):
        yv = targets_val[f"{sc}_severity_idx"].astype(int).values
        pred_val = _labels_for_scores(sc, scores[sc])
        mult = _sigma_multiplier_for_variant(variant, sc, scores[sc], state, val_ids)
        best = (float(grid[0]), math.inf)
        for sig in grid:
            if variant in {"responses_rt_calibration_only", "responses_constant_softening", "responses_coverage_only_calibration", "responses_uncertainty_only_calibration", "responses_shuffled_rt_calibration"}:
                prob = _probs_for_scores_variable_sigma(sc, scores[sc], float(sig) * mult)
            else:
                prob = _probs_for_scores(sc, scores[sc], sigma=float(sig))
            ece = ece_score_with_fixed_pred(yv, prob, pred_val)
            if ece < best[1]:
                best = (float(sig), float(ece))
        return best

    def _test_metrics(scores, state, variant, sigma, sc):
        yt = targets_test[f"{sc}_severity_idx"].astype(int).values
        pred = _labels_for_scores(sc, scores[sc])
        mult = _sigma_multiplier_for_variant(variant, sc, scores[sc], state, test_ids)
        if variant in {"responses_rt_calibration_only", "responses_constant_softening", "responses_coverage_only_calibration", "responses_uncertainty_only_calibration", "responses_shuffled_rt_calibration"}:
            prob = _probs_for_scores_variable_sigma(sc, scores[sc], float(sigma) * mult)
        else:
            prob = _probs_for_scores(sc, scores[sc], sigma=float(sigma))
        eye = np.eye(prob.shape[1])
        return {
            "test_ece_label": ece_score_with_fixed_pred(yt, prob, pred),
            "test_brier": float(np.mean(np.sum((prob - eye[yt]) ** 2, axis=1))),
            "test_nll": multiclass_nll(yt, prob),
        }

    rows = []
    # Score-to-probability sigma grid for response-only and true RT calibration-only.
    for variant_label, variant in [("response_only_sigma", "responses"), ("true_rt_calibration_sigma", "responses_rt_calibration_only")]:
        scores_val, state_val = _scores_from_selected(val_ids, selected_val, variant, long)
        scores_test, state_test = _scores_from_selected(test_ids, selected_test, variant, long)
        for sc in SCALE_ORDER:
            sig0, val0 = _select_sigma(scores_val, state_val, variant, original_sigma_grid, sc)
            sig1, val1 = _select_sigma(scores_val, state_val, variant, expanded_sigma_grid, sc)
            met0 = _test_metrics(scores_test, state_test, variant, sig0, sc)
            met1 = _test_metrics(scores_test, state_test, variant, sig1, sc)
            rows.append({
                "check": variant_label,
                "scale": sc,
                "original_upper_bound": 6.0,
                "expanded_upper_bound": 10.0,
                "original_selected": sig0,
                "expanded_selected": sig1,
                "hit_original_upper_bound": bool(sig0 >= 6.0),
                "validation_metric_original": val0,
                "validation_metric_expanded": val1,
                "test_ece_label_original": met0["test_ece_label"],
                "test_ece_label_expanded": met1["test_ece_label"],
                "test_brier_original": met0["test_brier"],
                "test_brier_expanded": met1["test_brier"],
                "test_nll_original": met0["test_nll"],
                "test_nll_expanded": met1["test_nll"],
                "interpretation": "Expanded smoothing was selected for PSS; qualitative RT-specific conclusion unchanged." if sc == "pss" and sig1 > sig0 else "No qualitative change."
            })

    # Temperature scaling grid extension using response-only probabilities selected under the original sigma grid.
    scores_val, state_val = _scores_from_selected(val_ids, selected_val, "responses", long)
    scores_test, state_test = _scores_from_selected(test_ids, selected_test, "responses", long)
    base_sigma = {}
    for sc in SCALE_ORDER:
        base_sigma[sc], _ = _select_sigma(scores_val, state_val, "responses", original_sigma_grid, sc)
    prob_val = {sc: _probs_for_scores(sc, scores_val[sc], sigma=base_sigma[sc]) for sc in SCALE_ORDER}
    prob_test = {sc: _probs_for_scores(sc, scores_test[sc], sigma=base_sigma[sc]) for sc in SCALE_ORDER}
    pred_test = {sc: _labels_for_scores(sc, scores_test[sc]) for sc in SCALE_ORDER}
    for sc in SCALE_ORDER:
        yv = targets_val[f"{sc}_severity_idx"].astype(int).values
        yt = targets_test[f"{sc}_severity_idx"].astype(int).values
        def best_temp(grid):
            vals = [(float(T), multiclass_nll(yv, _temperature_scale(prob_val[sc], float(T)))) for T in grid]
            return min(vals, key=lambda x: x[1])
        T0, val0 = best_temp(original_temp_grid)
        T1, val1 = best_temp(expanded_temp_grid)
        p0 = _temperature_scale(prob_test[sc], T0)
        p1 = _temperature_scale(prob_test[sc], T1)
        eye = np.eye(p0.shape[1])
        rows.append({
            "check": "temperature_scaling_grid",
            "scale": sc,
            "original_upper_bound": 5.0,
            "expanded_upper_bound": 10.0,
            "original_selected": T0,
            "expanded_selected": T1,
            "hit_original_upper_bound": bool(T0 >= 5.0),
            "validation_metric_original": val0,
            "validation_metric_expanded": val1,
            "test_ece_label_original": ece_score_with_fixed_pred(yt, p0, pred_test[sc]),
            "test_ece_label_expanded": ece_score_with_fixed_pred(yt, p1, pred_test[sc]),
            "test_brier_original": float(np.mean(np.sum((p0 - eye[yt]) ** 2, axis=1))),
            "test_brier_expanded": float(np.mean(np.sum((p1 - eye[yt]) ** 2, axis=1))),
            "test_nll_original": multiclass_nll(yt, p0),
            "test_nll_expanded": multiclass_nll(yt, p1),
            "interpretation": "Expanded temperature selected; generic calibration smoothing remains stronger than RT-specific interpretation." if sc == "pss" and T1 > T0 else "No qualitative change."
        })
    out = pd.DataFrame(rows)
    out.to_csv(TABLE_DIR / "table14_calibration_grid_boundary_sensitivity_19.csv", index=False)
    return out


def run_stepwise_leakage_audit(long: pd.DataFrame) -> pd.DataFrame:
    cfg = load_config()
    rng = np.random.default_rng(cfg["seed"] + 12021)
    ids = rng.choice(load_ids("test"), size=min(25, len(load_ids("test"))), replace=False).astype(int).tolist()
    budget = 19
    base = simulate_item_selection("rt_aware_uncertainty", budget, ids, long=long, seed=cfg["seed"] + budget)
    sample = long[long["participant_id"].isin(ids)].copy()
    if "pair_key" not in sample.columns:
        sample["pair_key"] = sample["participant_id"].astype(str) + "|" + sample["global_item_id"].astype(str)
    rows = []
    for step in range(budget):
        prefix_pairs = set(str(pid) + "|" + item for pid, items in base.items() for item in items[:step])
        future_mask = ~sample["pair_key"].isin(prefix_pairs)
        for perturb_type, cols in [
            ("future_response", ["item_response"]),
            ("future_rt", ["raw_rt", "log_rt", "rt_residual_content_z", "rt_residual_conditioned_z"]),
        ]:
            pert = sample.copy()
            for col in cols:
                if col in pert.columns:
                    vals = pert.loc[future_mask, col].values.copy()
                    pert.loc[future_mask, col] = rng.permutation(vals)
            sel = simulate_item_selection("rt_aware_uncertainty", step + 1, ids, long=pert, seed=cfg["seed"] + budget)
            unchanged = sum(1 for pid in ids if sel[int(pid)][: step + 1] == base[int(pid)][: step + 1])
            rows.append({
                "audit": "stepwise_future_information_perturbation",
                "perturbation": perturb_type,
                "step_before_selection": step,
                "participants_checked": len(ids),
                "prefixes_unchanged": unchanged,
                "status": "PASS" if unchanged == len(ids) else "FAIL",
            })
    out = pd.DataFrame(rows)
    out.to_csv(TABLE_DIR / "table7b_stepwise_leakage_audit.csv", index=False)
    summary = out.groupby("perturbation", as_index=False).agg(
        prefixes_unchanged=("prefixes_unchanged", "sum"), participants_checked=("participants_checked", "sum")
    )
    summary["status"] = np.where(summary["prefixes_unchanged"] == summary["participants_checked"], "PASS", "FAIL")
    summary.to_csv(TABLE_DIR / "table7c_stepwise_leakage_summary.csv", index=False)
    return out


def _reliability_curve(y: np.ndarray, prob: np.ndarray, n_bins: int = 10) -> pd.DataFrame:
    conf = prob.max(axis=1); pred = prob.argmax(axis=1); correct = (pred == y).astype(float)
    bins = np.linspace(0, 1, n_bins + 1)
    rows = []
    for lo, hi in zip(bins[:-1], bins[1:]):
        mask = (conf > lo) & (conf <= hi)
        if mask.any():
            rows.append({"bin_mid": (lo + hi) / 2, "accuracy": correct[mask].mean(), "confidence": conf[mask].mean(), "n": int(mask.sum())})
    return pd.DataFrame(rows)


def generate_additional_figures(long: pd.DataFrame) -> None:
    _ensure_predictions(long)
    cfg = load_config()
    # Per-scale reliability diagram for response-only and RT calibration-only at 19 items.
    df_base = pd.read_csv(TABLE_DIR / "predictions_response_only_uncertainty_b19_responses.csv")
    df_rt = pd.read_csv(TABLE_DIR / "predictions_response_only_uncertainty_b19_responses_rt_calibration_only.csv")
    plt.rcParams.update({"font.family": "serif", "font.serif": ["Times New Roman", "Times", "Nimbus Roman", "Liberation Serif", "DejaVu Serif"], "font.size": 9, "axes.labelsize": 9, "axes.titlesize": 9, "xtick.labelsize": 8, "ytick.labelsize": 8, "legend.fontsize": 8})
    fig, axes = plt.subplots(2, 2, figsize=(7.16, 5.10), sharex=True, sharey=True)
    for ax, sc in zip(axes.ravel(), SCALE_ORDER):
        y = df_base[f"{sc}_true"].astype(int).values
        for label, df, marker in [("Response-only", df_base, "o"), ("RT calibration-only", df_rt, "s")]:
            cols = [c for c in df.columns if c.startswith(f"{sc}_prob_")]
            curve = _reliability_curve(y, df[cols].values.astype(float), 10)
            ax.plot(curve["confidence"], curve["accuracy"], marker=marker, linewidth=1.0, markersize=3.5, label=label)
            for point in curve.itertuples():
                ax.annotate(
                    f"n={int(point.n)}",
                    (point.confidence, point.accuracy),
                    xytext=(2, 2),
                    textcoords="offset points",
                    fontsize=5.5,
                    alpha=0.75,
                )
        ax.plot([0, 1], [0, 1], "--", linewidth=0.8)
        ax.set_xlim(-0.02, 1.02)
        ax.set_ylim(0, 1.05)
        ax.set_title(SCALE_NAMES[sc], pad=2)
        ax.set_xlabel("Mean confidence")
        ax.set_ylabel("Empirical accuracy")
    axes[0, 0].legend(frameon=False, loc="upper left")
    fig.tight_layout(pad=0.55, w_pad=1.0, h_pad=0.8)
    fig.savefig(FIG_DIR / "figure4_per_scale_reliability_diagrams.png", dpi=600, bbox_inches="tight", facecolor="white")
    fig.savefig(FIG_DIR / "figure4_per_scale_reliability_diagrams.pdf", bbox_inches="tight", facecolor="white")
    plt.close(fig)

    # Manuscript Figure 5: full-width calibration-control comparison.
    calib = pd.read_csv(TABLE_DIR / "table8_standard_calibration_baselines_19.csv")
    order = [
        "response_only_uncalibrated", "temperature_scaling", "one_vs_rest_isotonic",
        "constant_softening", "shuffled_rt_placebo", "true_rt_calibration_only", "rt_score_adjusted"
    ]
    labels = {
        "response_only_uncalibrated": "Response-only",
        "temperature_scaling": "Temperature",
        "one_vs_rest_isotonic": "Isotonic",
        "constant_softening": "Constant",
        "shuffled_rt_placebo": "Shuffled RT",
        "true_rt_calibration_only": "True RT cal.",
        "rt_score_adjusted": "RT score",
    }
    plot_df = calib.set_index("calibration_method").loc[order].reset_index()
    plot_df["label"] = plot_df["calibration_method"].map(labels)
    plot_df["uses_rt_plot"] = plot_df["calibration_method"].isin(["shuffled_rt_placebo", "true_rt_calibration_only", "rt_score_adjusted"])
    fig, axes = plt.subplots(1, 2, figsize=(7.16, 3.20), sharey=True)
    for ax, metric, xlabel in [(axes[0], "mean_ece", "ECE*"), (axes[1], "mean_brier_score", "Brier score")]:
        vals = plot_df[metric].astype(float).values
        y = np.arange(len(plot_df))
        bars = ax.barh(y, vals, edgecolor="black", linewidth=0.35)
        for bar, is_rt in zip(bars, plot_df["uses_rt_plot"]):
            if is_rt:
                bar.set_hatch("///")
        ax.set_yticks(y)
        ax.set_yticklabels(plot_df["label"])
        ax.invert_yaxis()
        ax.set_xlabel(xlabel)
        xmax = float(vals.max()) * 1.38
        ax.set_xlim(0, xmax)
        for yi, v in enumerate(vals):
            ax.text(v + xmax * 0.025, yi, f"{v:.3f}", va="center", fontsize=7.5, clip_on=True)
        ax.grid(axis="x", linewidth=0.25, alpha=0.4)
    fig.tight_layout(pad=0.75, w_pad=1.8)
    fig.savefig(FIG_DIR / "figure5_calibration_controls_comparison.png", dpi=600, bbox_inches="tight", facecolor="white")
    fig.savefig(FIG_DIR / "figure5_calibration_controls_comparison.pdf", bbox_inches="tight", facecolor="white")
    plt.close(fig)

    # Confusion matrices for response-only predictions at 19 items.
    fig, axes = plt.subplots(2, 2, figsize=(7.16, 4.9))
    for ax, sc in zip(axes.ravel(), SCALE_ORDER):
        labels = list(range(len(cfg["labels"][sc]["classes"])))
        cm = confusion_matrix(df_base[f"{sc}_true"].astype(int), df_base[f"{sc}_pred"].astype(int), labels=labels)
        im = ax.imshow(cm, aspect="auto")
        ax.set_title(SCALE_NAMES[sc])
        ax.set_xticks(labels); ax.set_yticks(labels)
        short = [x.replace("clinically_", "clin.").replace("moderately_severe", "mod.-sev.") for x in cfg["labels"][sc]["classes"]]
        ax.set_xticklabels(short, rotation=45, ha="right", fontsize=8)
        ax.set_yticklabels(short, fontsize=8)
        for i in range(cm.shape[0]):
            for j in range(cm.shape[1]):
                if cm[i, j] > 0:
                    ax.text(j, i, str(cm[i, j]), ha="center", va="center", fontsize=7)
        ax.set_xlabel("Predicted")
        ax.set_ylabel("True")
    fig.tight_layout(pad=0.4)
    fig.savefig(SUPP_FIG_DIR / "supplementary_figure_confusion_matrices_response_only_19.png", dpi=600, facecolor="white")
    fig.savefig(SUPP_FIG_DIR / "supplementary_figure_confusion_matrices_response_only_19.pdf", facecolor="white")
    plt.close(fig)


def main() -> None:
    ensure_dirs()
    t0 = time.perf_counter()
    long = fit_rt_residuals()
    _ensure_predictions(long)
    print("[analysis] standard calibration baselines", flush=True)
    run_standard_calibration_baselines(long)
    print("[analysis] learned mask-aware baselines", flush=True)
    run_learned_maskaware_baselines(long)
    print("[analysis] per-class error tables", flush=True)
    run_per_class_error_tables(long)
    print("[analysis] high-risk burden table", flush=True)
    run_high_risk_burden_table(long)
    print("[analysis] RT residual diagnostics", flush=True)
    run_rt_residual_sensitivity(long)
    print("[analysis] calibration-grid boundary sensitivity", flush=True)
    run_calibration_grid_boundary_sensitivity(long)
    print("[analysis] stepwise leakage audit", flush=True)
    run_stepwise_leakage_audit(long)
    print("[analysis] additional figures", flush=True)
    generate_additional_figures(long)
    elapsed = time.perf_counter() - t0
    pd.DataFrame([{"stage": "additional_analyses", "seconds": round(elapsed, 3)}]).to_csv(ROOT / "reports" / "additional_analysis_runtime_report.csv", index=False)
    print(f"Additional analyses completed in {elapsed:.1f}s", flush=True)


if __name__ == "__main__":
    main()
    # Some numerical libraries keep worker threads alive in this container;
    # force a clean process exit after all CSV/PDF/PNG outputs are flushed.
    sys.stdout.flush(); sys.stderr.flush(); os._exit(0)
