#!/usr/bin/env python
"""Check that manuscript tables and figures generated by both pipelines exist."""
from pathlib import Path
import sys
import pandas as pd
ROOT = Path(__file__).resolve().parents[1]
required_tables = [
    'results/tables/table1a_data_validation.csv',
    'results/tables/main_model_results.csv',
    'results/tables/table3_baseline_performance.csv',
    'results/tables/table4_ablation_results.csv',
    'results/tables/table8_standard_calibration_baselines_19.csv',
    'results/tables/table9_learned_maskaware_baselines.csv',
    'results/tables/table10_per_class_metrics_19.csv',
    'results/tables/table11_rt_residual_sensitivity_19.csv',
    'results/tables/table13_calibration_delta_bootstrap_19.csv',
    'results/tables/table14_calibration_grid_boundary_sensitivity_19.csv',
    'results/tables/table12_high_risk_burden_19.csv',
    'results/tables/table7b_stepwise_leakage_audit.csv',
    'results/tables/table15_shortform_error_profile.csv',
    'results/tables/table16_error_detection_models.csv',
    'results/tables/table17_selective_fullform_escalation.csv',
    'results/tables/table18_process_quality_strata.csv',
    'results/tables/table19_cross_scale_transfer.csv',
    'results/tables/table20_escalation_bootstrap_ci.csv',
    'results/tables/table21_ocw_threshold_sensitivity.csv',
    'results/tables/table22_per_scale_selective_escalation.csv',
    'results/tables/table24_non_pss_selective_escalation.csv',
    'results/tables/table25_detection_pr_auc_bootstrap.csv',
    'results/tables/table26_internal_consistency.csv',
    'results/tables/table27_score_level_sensitivity.csv',
]
frontiers_figures = [
    'results/frontiers_submission/main_figures/Figure_1_macro_F1_across_item_budgets.png',
    'results/frontiers_submission/main_figures/Figure_2_ECE_star_across_item_budgets.png',
    'results/frontiers_submission/main_figures/Figure_3_selective_full_form_escalation_frontier.png',
    'results/frontiers_submission/main_figures/Figure_4_process_quality_strata.png',
    'results/frontiers_submission/supplementary_figures/Supplementary_Figure_S1_rt_residualization.png',
    'results/frontiers_submission/supplementary_figures/Supplementary_Figure_S2_per_scale_reliability.png',
    'results/frontiers_submission/supplementary_figures/Supplementary_Figure_S3_calibration_controls.png',
    'results/frontiers_submission/supplementary_figures/Supplementary_Figure_S4_response_speed_subgroups.png',
]
legacy_figures = [
    'results/figures/figure1_rt_residualization.png',
    'results/figures/figure2_budget_performance.png',
    'results/figures/figure3_ece_by_budget.png',
    'results/figures/figure4_per_scale_reliability_diagrams.png',
    'results/figures/figure5_calibration_controls_comparison.png',
    'results/figures/figure6_subgroup_fnr.png',
    'results/figures/figure7_escalation_burden_frontier.png',
    'results/figures/figure8_process_quality_error_rates.png',
]
missing = [p for p in required_tables if not (ROOT / p).exists()]
# Compact Frontiers archives retain final figures under results/frontiers_submission;
# full regenerated runs may also contain the legacy results/figures files.
if not all((ROOT / p).exists() for p in legacy_figures):
    missing.extend(p for p in frontiers_figures if not (ROOT / p).exists())
if missing:
    print('Missing expected manuscript outputs:')
    for p in missing:
        print('  -', p)
    sys.exit(1)
required = required_tables
# Lightweight numerical checks to catch stale or partially regenerated outputs.
table8 = pd.read_csv(ROOT / 'results/tables/table8_standard_calibration_baselines_19.csv')
resp = float(table8.loc[table8['calibration_method'] == 'response_only_uncalibrated', 'mean_macro_f1'].iloc[0])
iso = float(table8.loc[table8['calibration_method'] == 'one_vs_rest_isotonic', 'mean_ece'].iloc[0])
true_rt = float(table8.loc[table8['calibration_method'] == 'true_rt_calibration_only', 'mean_ece'].iloc[0])
assert abs(resp - 0.6885556988052488) < 1e-6, f'unexpected response-only F1: {resp}'
assert abs(iso - 0.038) < 5e-4, f'unexpected isotonic ECE-L: {iso}'
assert abs(true_rt - 0.083) < 5e-4, f'unexpected true RT ECE-L: {true_rt}'

rt_score_ece = float(table8.loc[table8['calibration_method'] == 'rt_score_adjusted', 'mean_ece'].iloc[0])
rt_score_ecea = float(table8.loc[table8['calibration_method'] == 'rt_score_adjusted', 'mean_ece_argmax'].iloc[0])
assert abs(rt_score_ece - 0.085) < 5e-4 and abs(rt_score_ecea - 0.079316) < 5e-4, f'unexpected RT score ECE fields: {rt_score_ece}, {rt_score_ecea}'
burden = pd.read_csv(ROOT / 'results/tables/table12_high_risk_burden_19.csv')
pss_flagged = int(burden[(burden['variant']=='Response-only') & (burden['scale']=='PSS')]['flagged_n'].iloc[0])
assert pss_flagged == 1430, f'unexpected PSS flagged_n: {pss_flagged}'
step = pd.read_csv(ROOT / 'results/tables/table7c_stepwise_leakage_summary.csv')
assert set(step['status']) == {'PASS'}, 'stepwise leakage summary did not fully pass'
grid = pd.read_csv(ROOT / 'results/tables/table14_calibration_grid_boundary_sensitivity_19.csv')
pss_rows = grid[(grid['scale']=='pss') & (grid['hit_original_upper_bound'].astype(str).str.lower().isin(['true','1']))]
assert len(pss_rows) >= 2, 'expected PSS sigma/temperature upper-bound sensitivity rows'
assert float(grid[(grid['check']=='response_only_sigma') & (grid['scale']=='pss')]['expanded_selected'].iloc[0]) >= 8.0, 'expected expanded PSS sigma grid to select stronger smoothing'

profile = pd.read_csv(ROOT / 'results/tables/table15_shortform_error_profile.csv')
allrow = profile[profile['scale'] == 'Mean / all scale-decisions'].iloc[0]
assert int(allrow['n_errors']) == 2270, f"unexpected 19-item error count: {allrow['n_errors']}"
assert int(allrow['n_overconfident_wrong']) == 579, f"unexpected OCW count: {allrow['n_overconfident_wrong']}"
table21 = pd.read_csv(ROOT / 'results/tables/table21_ocw_threshold_sensitivity.csv')
q75 = table21[table21['overconfidence_quantile'].round(2) == 0.75]
assert not q75.empty and int(q75['test_positive_n'].iloc[0]) == 579, '0.75 OCW-threshold sensitivity row does not match primary OCW definition'
metric_cols_21 = ['recall_at_top10pct', 'precision_at_top10pct', 'high_risk_fn_capture_at_top10pct']
assert table21[metric_cols_21].notna().all().all(), 'OCW-threshold sensitivity contains missing top-10% metrics'
selective = pd.read_csv(ROOT / 'results/tables/table17_selective_fullform_escalation.csv')
expected_strategies = {'random','confidence_only','rt_only','rt_plus_conf_error','rt_plus_conf_ocw','rt_plus_conf_hfn','shuffled_rt_placebo','oracle'}
assert expected_strategies.issubset(set(selective['strategy'])), 'selective escalation strategies missing'
rt20 = selective[(selective['strategy'] == 'rt_only') & (selective['escalation_rate'].round(2) == 0.20)]
assert len(rt20) == 1 and abs(float(rt20['overconfident_wrong_capture_rate'].iloc[0]) - 0.637306) < 5e-4, 'unexpected RT-only 20pct OCW capture'
ocw20 = selective[(selective['strategy'] == 'rt_plus_conf_ocw') & (selective['escalation_rate'].round(2) == 0.20)]
assert len(ocw20) == 1 and float(ocw20['overconfident_wrong_capture_rate'].iloc[0]) > 0.70, 'OCW-specific escalation detector did not capture expected OCW burden'
bootstrap = pd.read_csv(ROOT / 'results/tables/table20_escalation_bootstrap_ci.csv')
shared = bootstrap.merge(
    selective[selective['escalation_rate'].round(2) == 0.20],
    on='strategy',
    suffixes=('_table20', '_table17'),
)
for metric in ['error_capture_rate', 'overconfident_wrong_capture_rate', 'high_risk_fn_capture_rate']:
    delta = (shared[f'{metric}_table20'] - shared[f'{metric}_table17']).abs()
    assert (delta < 1e-12).all(), f'table20 base values differ from table17 for {metric}'
errdet = pd.read_csv(ROOT / 'results/tables/table16_error_detection_models.csv')
assert {'wrong','overconfident_wrong'}.issubset(set(errdet['target'])), 'error-detection targets missing'
ocw_auc = float(errdet[(errdet['target']=='overconfident_wrong') & (errdet['model']=='confidence_plus_rt')]['pr_auc'].iloc[0])
assert ocw_auc > 0.70, f'unexpectedly weak confidence+RT OCW PR-AUC: {ocw_auc}'
print(f'All {len(required_tables)} expected manuscript tables and final figures are present; key values match.')
